### ISSUE TITLE
ECONNRESET Loop after wifi reconnect

### ISSUE THREAD

**Issue by Vannixxo** [iRayanKhan/homebridge-tuya#141] opened 2020-10-20 10:49 UTC
Hello, after a wifi drop and reconnect, even if my tuya smart bulb successfully reconnected (and has fixed ip in the homebridge config), the plugin keeps sayin ECONNRESET clogging the homebridge log section and never reconnects to the bulb until the whole homebridge is rebooted.. while all the other accessories successfully reconnect. Plus, is there a way to disable logs in the console? I also found two times the bulb turned on by itself, don’t know if it is the plugin triggering it, as this never happened before homebridge.

**Comment by Vannixxo** [comment] 2020-10-21 08:35
![86274FC4-67D3-4991-88D7-F56F79957E5B](https://user-images.githubusercontent.com/56208089/96694708-12b17880-1389-11eb-95c9-640de6e6a267.jpeg)

This happens. Even when wifi didn’t drop, I find the light ON, and in the logs I have this...

**Comment by jeylites** [comment] 2020-12-08 08:38
I'm having the same issue, has this been solved?

If wifi drops out and comes back again, the bulb loses connection to the plugin but is able to communicate with the Tuya app.  A reboot to homebridge get's it connected again but then the cycle continues. If I recall correctly, it wasn't as bad on the previous plugin version.

I have two different kinds of RGBCW lights, GU10 and Downlights.  I have given a static IP to the lights and have listed it in the config too. Also note that I have the following setup for the downlights` "pingTimeout": 2147483, "connectTimeout": 2147483`

```
},
    "platforms": [
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "STAIRS LED 1",
                    "type": "RGBTWLight",
                    "manufacturer": "MOKO",
                    "model": "wifi+BLE Smart bulb",
                    "id": "###",
                    "key": "###",
                    "ip": "192.168.1.60:6667",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "maxWhiteColor": "221",
                    "colorFunction": "HSB",
                    "minBrightness": 10,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000,
                    "pingTimeout": 2147483,
                    "connectTimeout": 2147483
                },
                {
                    "name": "HALL TV SPOT 1",
                    "type": "RGBTWLight",
                    "manufacturer": "MOKO",
                    "model": "wifi+BLE Smart bulb",
                    "id": "###",
                    "key": "###",
                    "ip": "192.168.1.64:6667",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "maxWhiteColor": "221",
                    "colorFunction": "HSB",
                    "minBrightness": 10,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                },
                {
                    "name": "HALL TV SPOT 2",
                    "type": "RGBTWLight",
                    "manufacturer": "MOKO",
                    "model": "wifi+BLE Smart bulb",
                    "id": "####",
                    "key": "####",
                    "ip": "192.168.1.65:6667",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "maxWhiteColor": "221",
                    "colorFunction": "HSB",
                    "minBrightness": 10,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                },
                {
                    "name": "HALL TV SPOT 3",
                    "type": "RGBTWLight",
                    "manufacturer": "MOKO",
                    "model": "wifi+BLE Smart bulb",
                    "id": "####",
                    "key": "####",
                    "ip": "192.168.1.66:6667",
                    "dpPower": "20",
                    "dpMode": "21",
                    "dpBrightness": "22",
                    "dpColorTemperature": "23",
                    "dpColor": "24",
                    "maxWhiteColor": "221",
                    "colorFunction": "HSB",
                    "minBrightness": 10,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                },
                {
```

**Comment by jeylites** [comment] 2020-12-08 08:44
I think this new feature might be the cause `"Slowing down retry attempts"`

```
[TuyaAccessory] Socket had a problem and will reconnect to HALL TV SPOT 3 (ENOTFOUND)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
```

**Comment by ElphaX** [comment] 2021-05-20 06:48
Fixed in a prior revision.

**Closed by ElphaX** 2021-05-20 06:48 UTC
Labels: bug
