### ISSUE TITLE
SimpleBlinds "odd message..."

### ISSUE THREAD

**Issue by fraho67** [iRayanKhan/homebridge-tuya#66] opened 2020-04-04 08:52 UTC
Hi,

I saw that within the old repo there was an issue with simple blinds that are not responding giving an "odd message...." output in the Homebridge Terminal. I'm having this issue too. I can see the three blinds in Homekit with status closed, can tap on them getting an "opening"-message but nothing happens. Are you still at it fixing that?

**Comment by iRayanKhan** [comment] 2020-04-04 19:15
Yup I just had some unexpected delays, can you provide your devices schema to make it where I can see if it's the same as the others?

**Comment by fraho67** [comment] 2020-04-04 19:56
Currently I've installed the plugin called "Homebridge Tuya". Which command then is the right one for getting the schema?

**Comment by fraho67** [comment] 2020-04-04 21:00
I wasn't doing anything about these blinds for a couple of months, so I have forgotten those steps to obtain the device schema. I've noticed that the old process doesn't work no more but I already was going through many processes with @AMoo-Miki here https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/84
With the current plugin my Tuya Smart plug is working (which it didn't with the old plugin), that's why I'm hoping that the blinds will do it as well in the end.

**Comment by AlbertoAIG** [comment] 2020-04-06 11:11
I have the same issue and Home App show "Without answer" bought blinds. I have get schema recently with Ucomen Home.
Thanks

**Comment by AlbertoAIG** [comment] 2020-04-06 20:49
schema: '[{"mode":"rw","code":"switch_control","name":"\\u5f00\\u5173\\u63a7\\u5236","property":{"range":["on","stop","off"],"type":"enum"},"id":1,"type":"obj","desc":""},{"mode":"rw","code":"tr_timecon","name":"\\u884c\\u7a0b\\u65f6\\u95f4\\u914d\\u7f6e","property":{"unit":"s","min":10,"max":120,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time2","id":9,"type":"obj","desc":""},{"mode":"rw","code":"BlackLight","name":"\\u80cc\\u5149\\u5f00\\u5173","property":{"type":"bool"},"id":101,"type":"obj","desc":"\\u80cc\\u5149\\u53ef\\u63a7"}]',

Thanks you

**Comment by florian-1309** [comment] 2020-04-07 23:42
Hey! 
I think I have a similar problem.
This is my issue:
https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/167

 When I try “homebridge-tuya” with type “SimpleBlinds”: same problem as before 

And when I try ”homebridge-tuya” with type “SimpleBlinds2”: I get the message that I haven’t defined a valid type

**Comment by iRayanKhan** [comment] 2020-04-07 23:51
So SimpleBlinds2 exists in the schema and documentation, but I am still testing it. I nailed the final bullet, and I can fully guarantee within the new few hours a new beta will be published to add SimpleBlinds2 Support.

I really appreciate everyones patience with this plugin, my schedules been wild with this whole virus thing, I hope everyone stays safe too.

**Comment by florian-1309** [comment] 2020-04-07 23:55
THANK YOU for your work!!! :-)
And stay safe!!!

**Comment by iRayanKhan** [comment] 2020-04-08 05:36
Try this:
```
sudo npm i -g homebridge-tuya@rc1
```

**Comment by AlbertoAIG** [comment] 2020-04-08 08:20
Hi, I tried but show version not found.

Thanks

**Comment by iRayanKhan** [comment] 2020-04-08 08:40
Replace @rc1 with @1.0.1

**Comment by AlbertoAIG** [comment] 2020-04-08 08:45
Thank you.
Now blinds show home app but if I try open or close nothing happen, any idea?

Thanks you again!
Regards

**Comment by fraho67** [comment] 2020-04-08 08:57
Hi,

as I am not at home currently I did not install the rc-Version so far. With the regular version I can also already see the blinds within the home app but nothing happens  when tapping on the icons  - except that it says "opening". @AlbertoAIG Are you also getting "odd message....." within the homebridge terminal for your blinds?

**Comment by florian-1309** [comment] 2020-04-08 10:59
Same problem. Have tested it with “SimpleBlinds2”. But now, nothing happens.

**Comment by iRayanKhan** [comment] 2020-04-08 18:06
Can you please remove your cached accessories, and if possible persist? Deleting persist means you will have to re-add your homebridge devices and I know that isn't suitable for everyone so it's a last resort.

**Comment by iRayanKhan** [comment] 2020-04-08 18:07
Also make sure you are on Rc1 or @1.0.1

**Comment by AlbertoAIG** [comment] 2020-04-08 18:16
Hi, I have 1.0.1 and I reset rasberryPi (I relieve this clear accessory cache) but they is not working, every show good Home app, opening o closing message work but blinds don't.

What can I do?

Thanks you,
Regards

**Comment by iRayanKhan** [comment] 2020-04-08 18:54
Restarting the Pi doesn’t remove accessory cache. Can you provide logs when you try to open/close your blinds?

**Comment by AlbertoAIG** [comment] 2020-04-08 20:08
Hi,

How can I remove accessory cache?

Thanks
Regards

**Comment by iRayanKhan** [comment] 2020-04-09 17:52
Go into your home bridge directory, make sure home bridge is stopped, then in the home bridge directory type
sudo rm -rf accessories/

**Comment by fraho67** [comment] 2020-04-10 08:57
I've installed 1.0.1 and deleted accessories but am still getting "odd message......" for the blinds when leaving it as "simpleblinds". When changing it "simpleblinds2" I am getting "Discovered a device that has not been configured yet....." and then in a loop [TuyaDiscovery] UDP from 192.168.0.113:6667 0x000055aa...0x0000aa55"

**Comment by florian-1309** [comment] 2020-04-13 20:19
Maybe dpAction is wrong. 

With this setting, I think opening (“2“: “1 “) and stopping (“Blinds saw change to 3“) work. But closing (“2“: “2“) doesn‘t work.

![FAFA90AC-37F8-492A-9DF9-A016B6F005D7](https://user-images.githubusercontent.com/61319886/79157337-b61b4280-7dd4-11ea-930b-b65e6f888965.jpeg)
![7EB8813F-26DE-414A-B26F-C66DD609AF0A](https://user-images.githubusercontent.com/61319886/79157351-ba476000-7dd4-11ea-90d2-813ad20ba46c.jpeg)
![5D2F970E-94D0-4AF6-9581-B738ECE56773](https://user-images.githubusercontent.com/61319886/79157353-badff680-7dd4-11ea-9feb-87d83728e385.jpeg)

**Comment by iRayanKhan** [comment] 2020-04-13 22:23
#75 seems to have pointed out why it isn't working. Creating some variation may work, will have to see depending on the blinds.

**Comment by iRayanKhan** [comment] 2020-04-13 22:23
@florian-1309 what is your schema? I can try to find the close command from there.

**Comment by iRayanKhan** [comment] 2020-04-13 22:24
And for anyone else, try Florian's method and see if it works for you.

**Comment by AlbertoAIG** [comment] 2020-04-13 22:27
> Go into your home bridge directory, make sure home bridge is stopped, then in the home bridge directory type
> sudo rm -rf accessories/

Hi, I did it but now I have odd message again

Thanks

**Comment by iRayanKhan** [comment] 2020-04-13 22:28
Alberto can you try Florian's method by modifying the config?

**Comment by AlbertoAIG** [comment] 2020-04-13 22:37
> Alberto can you try Florian's method by modifying the config?

Hi, I did it and odd message disappears but still don’t open or close the blind 
Thanks

**Comment by iRayanKhan** [comment] 2020-04-13 22:38
Try clearing accessories again?

**Comment by AlbertoAIG** [comment] 2020-04-13 22:47
> Try clearing accessories again?

Yes but  it doesn’t work

**Comment by iRayanKhan** [comment] 2020-04-13 23:21
Does it give any error messages or say anything?

**Comment by AlbertoAIG** [comment] 2020-04-13 23:32
> Does it give any error messages or say anything?

No, any message log panel

**Comment by florian-1309** [comment] 2020-04-14 00:00
The schema:
![02C44E4B-4CDE-4EC9-BABA-8DC7E899813D](https://user-images.githubusercontent.com/61319886/79171954-a6f7bd00-7df3-11ea-9836-51101bbaf730.jpeg)

**Comment by iRayanKhan** [comment] 2020-04-14 01:57
Try:

```
sudo npm I -g homebridge-tuya@1.0.2
```

**Comment by florian-1309** [comment] 2020-04-14 03:07
Have tried it with several configurations. Nothing worked. Have tried „SimpleBlinds“, “SimpleBlinds2“. With my additional configurations (“cmdOpen“, “cmdClose“,.....) and without. But nothing worked.

What configurations should I use?
Have you found out what‘s the close command?

**Comment by iRayanKhan** [comment] 2020-04-14 03:49
Could 3 be the close command? I can't tell from the schema.

Try opening / closing it using the Tuya app you are using and look in the home bridge console for what command gets sent.

**Comment by fraho67** [comment] 2020-04-14 06:37
I've deleted accessories once more, added Florian's parameters, installed sudo npm i -g homebridge-tuya@1.0.2 and restarted. The blinds now do not show up no more in Apples Home app and in Homebridge Terminal I get  "Rollladen (0402268384f3ebea974a) doesn't have a valid type defined" .......and in a loop [TuyaDiscovery] UDP from 192.168.0.111:6667 0x000055aa...0x0000aa55 

When changing to "SimpleBlinds" instead of "SimpleBlinds2" the blinds reappear but again there is this "odd message...." and nothing happens when tapping on the icons.

**Comment by AlbertoAIG** [comment] 2020-04-14 07:28
Hi, 
I've update to 1.0.2, remove accessory cache and it still doesn't work. :(

**Comment by florian-1309** [comment] 2020-04-14 13:00
I‘m really disappointed. Nothing works.
When I try to move the curtain with Tuya App, by hand or by remote control, the console tells me that 1 is opening, 2 is closing and 3 is stopping (almost sure that this is more or less right). 
But it‘s interesting:
If dpAction = 1, opening (“1“: “1“) is possible but closing (“1“: “2“) is not. And the same with dpAction = 2: In this case, (“2“: “1“) is also possible but closing (“1“: “2“) is not! The only difference between dpAction = 1 and dpAction = 2 is that with dpAction = 1, changes are called as „undefined“. With dpAction = 2, this is not the case (here, they are defined).

All in all, the problem is the closing. I have invested many hours now and I have absolutely no idea.

**Comment by fraho67** [comment] 2020-04-14 13:33
Can someone here point me to instructions of how to obtain the device schema?

**Comment by florian-1309** [comment] 2020-04-14 13:39
Type “tuya-lan-find --schema“ in your console and do the steps which you have done for finding out the id and key of your devices.

**Comment by fraho67** [comment] 2020-04-14 13:42
Thanks, but that's why I'm asking: If I understood correctly the steps I did last year do not work no more (the ones with my iPhone) (?)

**Comment by florian-1309** [comment] 2020-04-14 13:44
Let me guess: it doesn‘t find any key’s or id‘s anymore, right?

**Comment by fraho67** [comment] 2020-04-14 13:46
Haven't tried it so far because I read that it's no more working

**Comment by florian-1309** [comment] 2020-04-14 13:49
This is the case since the new Tuya App-Updates. I have installed an Emulator on my computer, installed an earlier version of Tuya as apk (you can find earlier versions online), set up proxy at this emulator and then, it works. 
Alone for this, I have invested hours of work.😂🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by fraho67** [comment] 2020-04-14 14:03
I've already invested hours of work last year including being set on wrong tracks and it never worked. I won't do that once more. Maybe some kind of miracle will happen some day and we are able to control these Tuyablinds via Homekit. Did you also try the webapi-plugin?

**Comment by tonysprenk** [comment] 2020-04-14 14:09
@fraho67 have a look at. [ESP-HomeKit-Devices](https://github.com/RavenSystem/esp-homekit-devices) . If your device has an ESP chip inside you can use [tuya-convert](https://github.com/ct-Open-Source/tuya-convert) to put ESP-HomeKit-Devices firmware on it and be forever free of the clutches of Tuya.

**Comment by florian-1309** [comment] 2020-04-14 14:16
@fraho67 Is the curtain compatible with Webapi-Plugin?

**Comment by fraho67** [comment] 2020-04-14 14:19
No, I don't think so, that's what I tried first and didn't work too. My devices are these ones https://www.amazon.de/gp/product/B07PS5LRPQ/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1
So how do I find out if there is an ESP chip inside?

**Comment by florian-1309** [comment] 2020-04-14 14:24
I guess you mean this https://github.com/basdelfos/homebridge-tuya-web#readme 
Right?
I have no idea if it’s possible to define the curtain as switch in the web api. I have thought about it many times in the past. But never really tried it.

I have no Switch, only the curtain. But that should make no difference.

**Comment by tonysprenk** [comment] 2020-04-14 14:41
@fraho67 Google the MAC adres. If it says that the chip is made by espressif it’s an ESP.

**Comment by tonysprenk** [comment] 2020-04-14 14:53
@fraho67 [Looks](https://templates.blakadder.com/etersky_WF-CS01.html) like it has been flashed with tasmota before, which is a good indication that it has an ESP inside. Although some manufacturers are known to be using different types of chips in the same products. Googling the MAC adres wil give you  a more reliable answer.

**Comment by florian-1309** [comment] 2020-04-14 15:16
@fraho67 Wouldn‘t it be possible for you to define your switch as multi-outlet for example (I have another switch with only one button which I have defined as outlet) (or maybe define it as switch if this is possible) then you assign a function to every button in the Tuya App and therefore, you can control your switch and hence, your curtain through HomeKit?
Then, you would have the possibility to press close, open and stop. But you wouldn’t have the percentage information. But the percentage information confuses anyway because the blinds in the HomeKit app moves up and down and the curtain moves left and right. Hence, I think the percentage is confusing anyway and not sooo useful.

According to ESP, what’s with the guarantee of the device if you do this?? One time, I flashed my motherboard of my computer. Then it was damaged and my money was gone. I would never do something like that if you don‘t know exactly what happens when you are doing this.

**Comment by florian-1309** [comment] 2020-04-14 15:33
> @fraho67 Wouldn‘t it be possible for you to define your switch as multi-outlet for example (I have another switch with only one button which I have defined as outlet) (or maybe define it as switch if this is possible) then you assign a function to every button in the Tuya App and therefore, you can control your switch and hence, your curtain through HomeKit?
> Then, you would have the possibility to press close, open and stop. But you wouldn’t have the percentage information. But the percentage information confuses anyway because the blinds in the HomeKit app moves up and down and the curtain moves left and right. Hence, I think the percentage is confusing anyway and not sooo useful.
> 
> According to ESP, what’s with the warranty of the device if you do this?? One time, I flashed my motherboard of my computer in an not-official way. Then it was damaged and my money was gone. I would never do something like that if you don‘t know exactly what happens when you are doing this.

https://youtu.be/kx14_hWALLA
😂😂😂

**Comment by florian-1309** [comment] 2020-04-14 16:21
> @fraho67 Wouldn‘t it be possible for you to define your switch as multi-outlet for example (I have another switch with only one button which I have defined as outlet) (or maybe define it as switch if this is possible) then you assign a function to every button in the Tuya App and therefore, you can control your switch and hence, your curtain through HomeKit?
> Then, you would have the possibility to press close, open and stop. But you wouldn’t have the percentage information. But the percentage information confuses anyway because the blinds in the HomeKit app moves up and down and the curtain moves left and right. Hence, I think the percentage is confusing anyway and not sooo useful.
> 
> According to ESP, what’s with the warranty of the device if you do this?? One time, I flashed my motherboard of my computer in an not-official way. Then it was damaged and my money was gone. I would never do something like that if you don‘t know exactly what happens when you are doing this.

Have tested it with my one button switch. That works really fast. 😳😄☺️ Don‘t know if this would also work with a 3-button curtain switch.

**Comment by fraho67** [comment] 2020-04-14 16:55
So I tried to be an outlaw too 😆 by defining one of my blindswitches as "multioutlet" and then "outlet" and then as "GarageDoor" but neither of them is working......odd message 😒 Thanks anyway for your efforts!

**Comment by florian-1309** [comment] 2020-04-14 20:10
I have a switch similar to this https://www.amazon.de/BSEED-Smart-WiFi-Berührungssensorschalter-Neutral-Feed-erforderlich-Kompatibel-Panel-Wandlichtschaltern/dp/B07PWB4R4T/ref=mp_s_a_1_3?dchild=1&keywords=bseed+lichtschalter+wifi&qid=1586894390&sprefix=bseed+lichtschalter&sr=8-3

With my setting described above, if you push the button, the curtain closes immediately. Again a push and it opens! You can push the switch physically or through HomeKit App. If you use the HomeKit App, the Switch changes the status as if you would have pushed it physically.
I have configured the switch as outlet.

If we don‘t find a solution to the above problem (and I’m not very optimistic anymore), I am almost sure that I will buy a second switch for the curtain-purpose.

**Comment by philmue1988** [comment] 2020-04-17 14:03
so i bought 3 different tuya switchs on Amazon and tried all 3 and it´s still not working ;/ When i change it from "SimpleBlinds" to "Outlet" e.g. than its possible to control

**Comment by philmue1988** [comment] 2020-04-17 14:06
also as "garagedoor" its working

**Comment by AlbertoAIG** [comment] 2020-04-17 14:14
I have got the data from the accessories supposedly fine, but it doesn't work for me anyway.  I just tried garage door and nothing.  What can be?  The switch or the data?

Thanks

**Comment by philmue1988** [comment] 2020-04-17 14:15
when i press the controlbuttons manually ( when definied as "SimpleBlinds") as get these messages  : 
Apr 17 15:13:25 raspberrypi homebridge[23357]: [TuyaAccessory] Blinds saw change to true
Apr 17 15:13:26 raspberrypi homebridge[23357]: [TuyaAccessory] Heard back from My Simple Blinds with command 8
Apr 17 15:13:26 raspberrypi homebridge[23357]: [TuyaAccessory] Blinds saw change to undefined
Apr 17 15:13:26 raspberrypi homebridge[23357]: [TuyaAccessory] Heard back from My Simple Blinds with command 8
Apr 17 15:13:26 raspberrypi homebridge[23357]: [TuyaAccessory] Blinds saw change to undefined
Apr 17 15:13:29 raspberrypi homebridge[23357]: [TuyaDiscovery] UDP from 192.168.2.105:6667 0x00005

but trying in Home, there is reaction

**Comment by florian-1309** [comment] 2020-04-17 14:50
> I have got the data from the accessories supposedly fine, but it doesn't work for me anyway. I just tried garage door and nothing. What can be? The switch or the data?
> 
> Thanks

Which switch do you have?

**Comment by florian-1309** [comment] 2020-04-17 15:02
@iRayanKhan Have you any idea what we could do for making “SimpleBlinds / SimpleBlinds2“ work? :/
Otherwise I will use a switch and define it as “Outlet“.

But I just wanted to ask you if you have found any solution for „Simple Blinds / SimpleBlinds2).

**Comment by AlbertoAIG** [comment] 2020-04-17 15:53
【LED Controlable】WiFi Interruptor Persiana, Maxcio Interruptor Inteligente Compatible con Alexa y Google Home, Control de APP y Función de Temporizador, para Motor Persiana, Motor de Obturador https://www.amazon.es/dp/B07NKNCNJV/ref=cm_sw_r_cp_api_i_rdDMEb5N3S6Y0

That’s

**Comment by florian-1309** [comment] 2020-04-17 16:45
@AlbertoAIG 
I have no idea if such curtain switches can be defined as outlet. But my tuya light Switch can be defined as one.

**Comment by AlbertoAIG** [comment] 2020-04-18 16:19
The truth is that I have a doubt. When I used a program to capture the schema, the key and so on I had to use a different one from "Tuya", add the switches and get them. Then I deleted that app again and added them back to the previous application. By doing that, does any of that data change? I say this because I am unable to make it work by switching between the different devices present in the plugin and from what you say, opening some works for example and nothing works for me.

Thank you

**Comment by iRayanKhan** [comment] 2020-04-20 20:42
Nope Currently I have no found any way to make Simple Blinds or Simple Blinds 2 to work. I really don't see what's different between the custom commands and why it won't accept them. The only theory I have is that it doesn't like the open duration or extra parameters even though the schema still spits it out. 

Sadly as I don't have any smart blinds I can do any testing on my own and don't get why it wouldn't work. 

If the outlet way works, you could add a fake-blinds accessory and create an automation in the home app so when the blinds accessory opens, it turns that switch on.

**Comment by florian-1309** [comment] 2020-04-21 01:32
Cool idea!
I have known that there is the possibility to create fake switches and fake lights. 
But there is also the possibility to create a fake blinds accessory? How can I do that?

**Comment by iRayanKhan** [comment] 2020-06-07 03:35
Hi @florian-1309,

The creator of Homebridge has a plugin called homebridge-dummy which you can use for making fake switches.

**Comment by JuniorGenius** [comment] 2020-08-28 09:30
Any updates on this? It was working fine for me until I re-paired my curtains and now I'm having that issue. I even modified the code to be more compatible with my blinds and even so it happens. Nothing should've changed..

**Comment by AndrewJ1990** [comment] 2020-08-31 09:37
I'm having this issue too, the blinds just not responding to either simpleblinds or simpleblinds2. Would the scheme of my device help at all? I'm happy to do some testing for you

**Comment by AndrewJ1990** [comment] 2020-09-01 08:10
Well I've managed to get it working so far. Ive changed from line 34-44 and it seems to be working. My Schema is below... The only thing it's not doing is changing its state in HomeKit if someone presses the button on the unit to open or close them.
      
```
 let _cmdOpen = 'open';
        if (this.device.context.cmdOpen) {
            _cmdOpen = ('' + this.device.context.cmdOpen).trim();
        }

        let _cmdClose = 'close';
        if (this.device.context.cmdClose) {
            _cmdClose = ('' + this.device.context.cmdClose).trim();
        }

        this.cmdStop = 'stop';
```


`  {
    name: 'Blind',
    id: '',
    key: ',
    def: {
      schema: '[{"mode":"rw","code":"control","name":"\\u63a7\\u5236","property":{"range":["open","stop","close"],"type":"enum"},"iconname":"icon-dp_power2","id":1,"type":"obj"},{"mode":"rw","code":"percent_control","name":"\\u5f00\\u542f\\u767e\\u5206\\u6bd4\\u63a7\\u5236","property":{"unit":"%","min":0,"max":100,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_power","id":2,"type":"obj"},{"mode":"ro","code":"percent_state","name":"\\u5f00\\u542f\\u767e\\u5206\\u6bd4\\u72b6\\u6001","property":{"unit":"%","min":0,"max":100,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_warming","id":3,"type":"obj"},{"mode":"rw","code":"control_back","name":"\\u7535\\u673a\\u53cd\\u5411","property":{"type":"bool"},"iconname":"icon-dp_time2","id":5,"type":"obj"},{"mode":"rw","code":"work_state","name":"\\u5de5\\u4f5c\\u72b6\\u6001","property":{"range":["opening","closing"],"type":"enum"},"id":7,"type":"obj"},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6","property":{"range":["cancel","1","2","3","4"],"type":"enum"},"id":8,"type":"obj"},{"mode":"ro","code":"countdown_left","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"unit":"s","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"id":9,"type":"obj"},{"mode":"ro","code":"fault","scope":"fault","name":"\\u6545\\u969c\\u544a\\u8b66","property":{"label":["motor_fault"],"type":"bitmap","maxlen":1},"id":10,"type":"obj"},{"mode":"ro","code":"time_total","name":"\\u5168\\u7a0b\\u8fd0\\u884c\\u65f6\\u95f4","property":{"unit":"ms","min":0,"max":120000,"scale":0,"step":1,"type":"value"},"id":11,"type":"obj"}]',
      extras: '[{"complexType":"","id":1,"inputStyle":"","inputType":" "},{"complexType":"","id":2,"inputStyle":"","inputType":" "},{"complexType":"","id":4,"inputStyle":"","inputType":" "},{"complexType":"","id":5,"inputStyle":"","inputType":" "},{"complexType":"","id":6,"inputStyle":"","inputType":" "},{"complexType":"","id":7,"inputStyle":"","inputType":" "},{"complexType":"","id":8,"inputStyle":"","inputType":" "},{"complexType":"","id":101,"inputStyle":"","inputType":"plain"}]',
    },
  },`

**Comment by iRayanKhan** [comment] 2020-09-01 14:32
@AndrewJ1990 do you have discord by chance?

**Comment by AndrewJ1990** [comment] 2020-09-01 19:14
@iRayanKhan Yeah I do. "Jochsey"

**Comment by iRayanKhan** [comment] 2020-09-01 19:19
@AndrewJ1990 whats your tag? It's the number after the #.

**Comment by AndrewJ1990** [comment] 2020-09-01 19:20
@iRayanKhan sorry! It's #7339

**Comment by ReconCubed** [comment] 2020-11-11 03:00
> Maybe dpAction is wrong.
> 
> With this setting, I think opening (“2“: “1“) and stopping (“Blinds saw change to 3“) work. But closing (“2“: “2“) doesn‘t work. I mean the curtain opens. But it doesn‘t close.
> 
> ![FAFA90AC-37F8-492A-9DF9-A016B6F005D7](https://user-images.githubusercontent.com/61319886/79157337-b61b4280-7dd4-11ea-930b-b65e6f888965.jpeg)
> ![7EB8813F-26DE-414A-B26F-C66DD609AF0A](https://user-images.githubusercontent.com/61319886/79157351-ba476000-7dd4-11ea-90d2-813ad20ba46c.jpeg)
> ![5D2F970E-94D0-4AF6-9581-B738ECE56773](https://user-images.githubusercontent.com/61319886/79157353-badff680-7dd4-11ea-9feb-87d83728e385.jpeg)

Was your signature just `{“3”:”2”}`? I’ve got a really complex signature that I’m trying to make sense of here: `{"1":"stop","2":50,"3":0,"5":false,"7":"opening","8":"cancel","9":0,"10":0,"11":32960}`

**Comment by ReconCubed** [comment] 2020-11-12 05:57
@AndrewJ1990 Thanks for this, help me fixed my issue #153 . You can just change the `cmdOpen`, `cmdStop`, and `cmdClose` parameters in the device config to those values, works perfectly after that.

If anyone else is looking, this worked for me:

This worked for me:
```
“cmdOpen”: “open”,
“cmdClose”: “close”,
“cmdStop”: “stop”,
“dpAction: 1
```

**Comment by biosim500** [comment] 2020-12-17 01:11
> @AndrewJ1990 Thanks for this, help me fixed my issue #153 . You can just change the `cmdOpen`, `cmdStop`, and `cmdClose` parameters in the device config to those values, works perfectly after that.
> 
> If anyone else is looking, this worked for me:
> 
> ```
> “cmdOpen”: “open”,
> “cmdClose”: “close”,
> “cmdStop”: “stop”,
> “dpAction: 1
> ```

I didn't quite get how you put this in config without an error sir!
Could you be more specific?

**Comment by iRayanKhan** [comment] 2021-02-15 04:51
@AndrewJ1990 would you like to make a PR for this? I'd be willing to merge it in.

**Comment by AndrewJ1990** [comment] 2021-02-15 05:34
@iRayanKhan I ended up just doing what @ReconCubed suggested above and adding the values to the config. I also don't know how to do a PR sorry

**Comment by iRayanKhan** [comment] 2021-02-19 20:43
If it works then no need for a PR it seems. Closing

**Closed by iRayanKhan** 2021-02-19 20:43 UTC
Labels: device-addition

**Comment by JuniorGenius** [comment] 2021-04-30 08:01
I still have this issue and I don't really understand what the solution is. I've tried changing my config as documented above with no success.
A while back I modified my local code to support my curtains' requests but it was not up to PR standards. Can someone please explain how to fix this issue?
